@echo off
:: Make the script location-independent: run everything relative to this file's
:: folder so .env, certs\, and `bun run ./src/main.ts` always resolve the same
:: way whether double-clicked or called by full path.
cd /d "%~dp0"
setlocal
TITLE Copilot API Proxy (HTTPS 8443)

echo ================================================
echo  GitHub Copilot API Proxy - HTTPS
echo  Port: 8443
echo ================================================
echo.

:: Load environment variables from .env if it exists
if exist .env (
    echo Loading environment from .env...
    for /f "usebackq tokens=1,* delims==" %%A in (".env") do (
        if not "%%A"=="" if not "%%A:~0,1%"=="#" (
            set "%%A=%%B"
        )
    )
    echo.
)

:: --- Port + TLS / HTTPS configuration ---------------------------------
set "PORT=8443"
:: LAN IP the other laptop uses to reach this PC (must match a cert SAN).
set "LAN_IP=192.168.0.105"
:: Point the server at the self-signed cert generated by generate-cert.bat.
set "TLS_CERT=%~dp0certs\server.crt"
set "TLS_KEY=%~dp0certs\server.key"

if not exist "%TLS_CERT%" (
    echo TLS certificate not found at "%TLS_CERT%".
    echo Run generate-cert.bat first to create it.
    echo.
    pause
    exit /b 1
)

:: Build if dist/ doesn't exist
if not exist dist (
    echo Building project...
    bun run build
    echo.
)

if defined TAVILY_API_KEY (
    echo Web search: enabled ^(Tavily^)
) else if defined BRAVE_API_KEY (
    echo Web search: enabled ^(Brave^)
) else (
    echo Web search: disabled ^(set TAVILY_API_KEY or BRAVE_API_KEY in .env to enable^)
)
echo.

echo Starting server on https://localhost:%PORT%
echo Reachable from other machines at https://%LAN_IP%:%PORT%
echo.

bun run ./src/main.ts start --port %PORT%
pause
endlocal
